import Head from 'next/head';
import { CreateCoverLetterPage } from '@/views/CreateCoverLetter';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create cover letter | Variant group test project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <CreateCoverLetterPage />
        </>
    );
}
